### ISSUE TITLE
issues resolved - ready for next 

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-Enterprise-class-networking#12]

**Comment by DawnmarieDesJardins** [comment]
Hi Michael,
I can't merge this one, it has conflicts and I don't know how to do resolve conflicts yet.  It looks like someone else created a pull request for broken links in the HOLs (18 days ago) but I'm assuming your April update will have fixed those so I think we can probably just delete that request as resolved?

**Comment by mwasham** [comment]
correct
