### ISSUE TITLE
Duplicate folders

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Enterprise-class-networking#15]
Hey Michael,
I started to go in and update this repo with the most current abstracts your team sent over and I'm seeing duplicate files in the workshop.  There are two WDS student guides, and two WDS trainer guides.  In the labs folder, there's Before the hands-on lab and Before the lab (should be Before the HOL).

I've updated the ReadMe file with the latest info but not going to update the WDS or labs until file numbers are correct.  Please let me know when it's complete. Thanks

**Comment by mwasham** [comment]
resolved
