### ISSUE TITLE
HOL step by step vnet label typo

### ISSUE THREAD

**Issue by larryms** [Microsoft/MCW-Enterprise-class-networking#20]
In the HOL step by step document, exercise 5, task 1, step 5, it says  "On the Choose Virtual Network blade, choose WGVNet".  (also shows this in the screenshot)
I believe this incorrect, and should reference **WGVNet1** as there is no WGVNET in the lab.

**Comment by zobayer098** [comment]
fixed and updated. Thanks @larryms
