### ISSUE TITLE
December Update for review

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-Enterprise-class-networking#21]
Suggestions 
 - Update screenshots 
 - Take advantage of DDoS feature (WDS & Lab)
 - Use Azure Firewall (WDS & Lab)
 - Virtual Network Service Endpoints
 - Update for new features of ExpressRoute (WDS)

**Comment by DawnmarieDesJardins** [comment]
@Microsoft/enterprise-class-networking-sme-group 
Adding the SME group for review and discussion.

**Comment by DawnmarieDesJardins** [comment]
In update, please review Open issue #20

**Comment by DawnmarieDesJardins** [comment]
@mwasham 
Hi Michael, 
Please have your team move forward with this update.
Dawnmarie

**Comment by zobayer098** [comment]
Hands On Labs -
Updated Screenshots, spelling and instructions
Added DDoS Protection Plan to the VNet
Replaced existing barracuda firewall with Azure Firewall
Configured Azure Firewall with NAT Rules to traffic
WDS -
Now updating the WDS

**Comment by zobayer098** [comment]
completed.

**Comment by zobayer098** [comment]
assigned to @Jeff-Opsgility

**Comment by Jeff-Opsgility** [comment]
@DawnmarieDesJardins , we are complete, WITH spellcheck.  Thanks.
