### ISSUE TITLE
ARM template

### ISSUE THREAD

**Issue by FDMGoMeZ** [Microsoft/MCW-Enterprise-class-networking#25]
Hi can you share the ARM template discussed in the lab.

**Comment by DawnmarieDesJardins** [comment]
Hello!
I believe you'll find what you're looking for in the Before the Hands-on lab document.  Let me know if that's not what you're looking for.
Dawnmarie

**Comment by FDMGoMeZ** [comment]
Hi,

 

Ok tnx did not see that one sorry for that perfect tnx for the update.

 

 

Van: Dawnmarie DesJardins <notifications@github.com>
Beantwoorden - Aan: Microsoft/MCW-Enterprise-class-networking <reply@reply.github.com>
Datum: woensdag 27 maart 2019 om 01:26
Aan: Microsoft/MCW-Enterprise-class-networking <MCW-Enterprise-class-networking@noreply.github.com>
CC: FDMGoMeZ <frederik.demuyter@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Microsoft/MCW-Enterprise-class-networking] ARM template (#25)

 

Hello!
I believe you'll find what you're looking for in the Before the Hands-on lab document. Let me know if that's not what you're looking for.
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
Closing issue, resolved.
