### ISSUE TITLE
Suggested WDS updates

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Enterprise-class-networking#27]
1. Using the Azure Firewall for inbound/outbound traffic is nice. However, I'm not so sure about using it to filter traffic between application tiers (as at present). Between application tiers, I suggest using NSGs and ASGs. Using ASGs is nice because it allows us to showcase putting all tiers in the same subnet, decoupling network design from application architecture, while still giving full network isolation between tiers. We could even put in an objection/requirement regarding limited IP space and the need to be efficient yet future-proof. NSGs also means we can bring in NSG flow logs / traffic analytics

2. We should add more on Service Endpoints, they're not well covered at present. In particular, with Forced Tunnelling, Service Endpoints are important to ensure the route from VM to service (E.g. SQL Database) doesn't loop back via the on-premises environment. Also we can talk about the service firewalls, and (once GA) Service Endpoint Policy.

3. We could add a large-volume Internet/consumer facing app. That can use Azure firewall, WAF, DDoS Standard and perhaps even FrontDoor. Hard to justify using all those unless it's Internet-facing. However, adding a separate app effectively doubles the WDS, might be too much given time constraints.

**Comment by DawnmarieDesJardins** [comment]
@jtuliani 
Hi Jonathan, Please review open issue #24 and incorporate into this update.
Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
@jtuliani 
Hi Jonathan,
The SME review period has closed for this one and we have lead approval to move forward with your suggested updates.  Thanks, Dawnmarie

**Comment by polichtm** [comment]
1 and 2 have been added. 3 is currently out of scope

**Comment by DawnmarieDesJardins** [comment]
Closing with May 2019 update merge.
