### ISSUE TITLE
Name mismatch

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/MCW-Enterprise-class-networking#32]
Hi there, in exercise 3, task 2, step 3 says: 

> Repeat this procedure to add the **DataToMgmt** route using the following information:

But on the form bellow it the route name is:

> Route name: AppToMgmt

It seems the correct name is _AppToMgmt_. Could you please fix the name on step # 3? Thanks in advance. :)

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul.  Please review & advise.

**Comment by DawnmarieDesJardins** [comment]
Hi Armando.  I've just finished QCing and merging the September test/fix for this workshop.  This has been resolved.  Thanks!
