### ISSUE TITLE
Wrong screenshot 

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/MCW-Enterprise-class-networking#33]
Hi there,
On exercise 3, task 2, step 9, the screenshot is not correct. The final result of the steps looks like this:
![image](https://user-images.githubusercontent.com/15189226/65284404-423ee300-daee-11e9-9f6e-5ec6b2de6f40.png)

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul.  Please review and advise.

**Comment by DawnmarieDesJardins** [comment]
This has been resolved in the Sept 2019 test/fix.
