### ISSUE TITLE
New interface for vNet peering

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/MCW-Enterprise-class-networking#36]
In exercise 6, we have task 1 and task 2 to configure vNet peering. The interface for vNet peering has changed and we can configure both sides of the peering in one shot. 

This exercise needs maintenance and the steps need adjustment. 

This is how the new interface looks like:

![image](https://user-images.githubusercontent.com/15189226/65295740-2a2f8980-db17-11e9-8755-38c3454169f1.png)

**Comment by paulopsgility** [comment]
This was fixed in the latest test/fix
