### ISSUE TITLE
Wrong vNet name

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/MCW-Enterprise-class-networking#38]
Hi,
In exercise 7, task 4, step 4 we are direct to select a vNet that doesn't exist.

> In the Azure portal, navigate to the blade of the virtual network **WGVNet**, select DDoS protection, select Standard, and, in the DDoS protection plan drop-down list, select the DDoSprotection entry.
There is no WGVNet and it was never a request to create one. We have WGVNet**1** and WGVnet**2**, but no WGVNet.

**Comment by DawnmarieDesJardins** [comment]
This has been resolved in the Sept 2019 test/fix.
