### ISSUE TITLE
Yet another wrong screenshot

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/MCW-Enterprise-class-networking#39]
On exercise 8, task 4, step 2, the screenshot there is the same of to task 3, step 2. It should look like this (but the resource group): 
![image](https://user-images.githubusercontent.com/15189226/65360788-243cb580-dbb6-11e9-835a-89fd6ad94ba7.png)

**Comment by paulopsgility** [comment]
This was fixed in the latest test/fix
