### ISSUE TITLE
Issue in Exercise 4: Configure n-tier application and validate functionality

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-Enterprise-class-networking#45]
In **Exercise 4**,Task 2, Tried configuring an Availability Set with the Azure Load Balancer but failed even though load  balancer and the availability set are in the same region.
![image](https://user-images.githubusercontent.com/48020356/72528122-51f9e880-3890-11ea-8235-db4706e6b0ea.png)
![image](https://user-images.githubusercontent.com/48020356/72528211-8a012b80-3890-11ea-825c-6dcff8452712.png)

**Comment by paulopsgility** [comment]
@amalgireesh Looks to be a portal bug. We are looking into it.

**Comment by akn9050** [comment]
Please let us know if any update on this

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Hi Paul.  Please be advised, it looks like we have a 1/28/2020 delivery schedule for this workshop.  Dawnmarie

**Comment by paulopsgility** [comment]
Sorry for the late feedback. This is an Azure portal bug. As such I cannot "fix" the underlying bug. However, the workaround is relatively simple, you just choose "virtual machine" and choose the VMs as opposed to choosing "availability set" and choosing the VMs. 

Give me about an hour and I will update the guide.

**Comment by paulopsgility** [comment]
Issue resolved.

**Comment by amalgireesh** [comment]
Thanks for the update @paulopsgility
