### ISSUE TITLE
Issues in Exercise 11

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Enterprise-class-networking#49]
Hi,
In exercise 11 task 1 we need to create storage account in both the regions East US and South Central US not just one region ,so that it is available while configuring the NSG Flow logs settings.
Exercise 11 task 4 OnPremVM is created in  OnPremVMRG and not OnPremVNetRG.

Can you please update the changes.

**Comment by DawnmarieDesJardins** [comment]
Hello @srushti-714 
I've just merged a test/fix for this workshop.  I think it addresses both of your concerns.  Please review Exercise 11 and let us know.

**Comment by DawnmarieDesJardins** [comment]
@srushti-714 
Closing this issues as resolved with the last update/merge.  Please reopen if that is not the case.
