### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by paulopsgility** [microsoft/MCW-Enterprise-class-networking#51]
Here are our suggested updates for the June 2020 update. Please add any other suggestions or feedback to this issue.

- Update to leverage ExpressRoute Global Reach 
- Update PowerShell examples to use Az instead of AzRM
- Update diagrams to use the new Azure icons
- Replace "jump box" with Bastion (addresses issue #44)

**Comment by DawnmarieDesJardins** [comment]
Add to update:  Review & address Issue #47

**Comment by tracsman** [comment]
- Add ExpressRoute FastPath
- I'm not sure if we mentioned availability zones and the standard load balancer before. If so, that could be mentioned. Also new ExpressRoute gateway SKUs to take advantage of AZ.
- Mention, not sure if we need to show, IPv6 and how VNets can do dual stack now

**Comment by rdendtler** [comment]
Agree with comments above
 
In addition, could we:
- We may want to add in NAT Gateway
- Re-org?  I feel like it jumps a bit (create a vnet, then monitoring, then route tables, then bastion...
- Would love to see us build the from VNET, to S2S, then Bastion...

**Comment by nivedv** [comment]
I fully agree the order is bit disarrayed.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #52
