### ISSUE TITLE
RDP Access to WGWEB1

### ISSUE THREAD

**Issue by saimachi** [microsoft/MCW-Enterprise-class-networking#54]
Hello,

After creating a load balancer in Exercise 5, Task 2, I am asked to initiate an RDP session to WGWEB1, one of the virtual machines in the backend pool. I am assuming that the sessions should be initiated from LABVM. According to WGAppNSG1, only systems on the Management (10.7.2.0/25) subnet can access machines on the AppSubnet over RDP.

![image](https://user-images.githubusercontent.com/37318129/97666326-9bd84780-1a3a-11eb-8072-e0ba1e0c92c6.png)

Are there any issues in my environment that are preventing me from completing the connection? In the meantime, how should I try to ensure that my load balancing solution is working?

Thank you.

**Comment by dwnatwick** [comment]
@saimachi, Is your connection being blocked or are you just asking a general question regarding the RDP connection?  As for the testing of the load balancer, that is what you will do when you RDP into the VM.  You will use the LB public IP address to verify that you connect to one of the two web servers.  Please clarify your issue on the RDP connection and we will resolve this issue.  Thank you very much.

**Comment by saimachi** [comment]
@dwnatwick In Step 10 of Exercise 5, Task 2, it mentions that we should try to connect to WGWEB1 so we can access 10.8.0.100 (the LB private IP address) to ensure that the service is working. However, it is not possible to connect to WGWEB1 from a machine that it is not on the Management subnet, and so my connection is blocked. So, I was wondering if my inability to connect to WGWEB1 is a problem with my environment, or is just not possible at this stage.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #57
