### ISSUE TITLE
Creating a Bastion

### ISSUE THREAD

**Issue by saimachi** [microsoft/MCW-Enterprise-class-networking#55]
Hello,

Currently, I am working on Task 1 of Exercise 8 of the MCW lab. I am trying to place the Bastion host on a new AzureBastionSubnet. When I try to provide 10.7.0.0/25 as the subnet address, I receive the following error. I am also alerted that this conflicts with GatewaySubnet (10.7.0.0/29).

![image](https://user-images.githubusercontent.com/37318129/97727257-745e9a80-1a8d-11eb-8f78-75c540c67f10.png)

Moreover, the guide notes the /25 subnet mask. However, it seems that Azure requires a /27 mask. I created an AzureBastionSubnet with the network address 10.7.3.0/27. Should I proceed down this route and modify the firewall ACLs and route tables accordingly?

![image](https://user-images.githubusercontent.com/37318129/97727347-89d3c480-1a8d-11eb-93a3-e283a6de80bd.png)

Thank you.

**Comment by arnoldojperozo** [comment]
Same happen to me ... Bastion subnet overlaps Gateway Subnet

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #56

**Comment by saimachi** [comment]
Hello,

I notice that you changed the subnet mask to be /27. However, 10.7.0.0/27 still interferes with GatewaySubnet. For now, I am using 10.7.3.0/27 as my Bastion subnet. I will let you know if this works.
