### ISSUE TITLE
I was able to connect WGSQL1 also

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Enterprise-class-networking#59]
Before Exercise 10: Create a Network Monitoring Solution

I was testing the following scenario;

On the jump host virtual machine (WGMGMT1), initiate a Remote Desktop session to the WGWEB1 via its private IP address (10.8.0.4). This should be successful since it is allowed by Azure Firewall.  --> this part is working as it supposed to be

**_However, an attempt to connect via Remote Desktop to the WGSQL1 via its private IP address should fail since it is blocked by a network security group._** --> I was able to connect to WGSQL1 also. 

![image](https://user-images.githubusercontent.com/4159116/99668794-3dbde380-2a7f-11eb-8ee2-c30add9df6d3.png)

Note: I created the WGMGMT1 VM in WGVNet1 --> Management Subnet

**Comment by fatihdurgut** [comment]
I just realized that last scenario is like below. 

On the jump host virtual machine (WGMGMT1), initiate a Remote Desktop session to the WGSQL1 via its private IP address (10.8.1.4). This should be successful since it is allowed by Azure Firewall.

So there is an inconsistency in the document with scenarios 3 and 4 with 5

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #60
