### ISSUE TITLE
Exercise 5, Task 2, Step 10 not possible due to Network Security Group settings

### ISSUE THREAD

**Issue by cyberyarek** [microsoft/MCW-Enterprise-class-networking#61]
Can't do an RDP session to WGWEB1 as the WGAppNSG1 network security group allows access to RDP only from Management subnet (inbound rule 200: AllowMgmtInboundAny3389).  This can only be done from the Management subnet.  Trouble is that previous instructions do not direct to create an admin server in Management subnet (10.7.2.0/25) in WGVNet1 (with appropriate NSG settings for that server to allow RDP into it or use of Bastion).  Neither is that indicated in the "Before the HOL" doc.

**Comment by DawnmarieDesJardins** [comment]
@cyberyarek 
Hi Yarek.  I just pushed through PR #60 that may solve your issue.  Please retry and let us know if you're still having trouble.

**Comment by DawnmarieDesJardins** [comment]
No further communication from field, closing issue.  Please reopen if needed.
