### ISSUE TITLE
Screenshot updation needed in Exercise 1, Task 2

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-Enterprise-class-networking#65]
Requesting screenshot updation in Exercise 1, Task2, Step 4 & 5 with the latest Azure GUI.
Attaching the new screenshots below for reference.
 
![image](https://user-images.githubusercontent.com/48020356/124064756-0ff83e80-da53-11eb-84ce-9a6e988d866b.png)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #66
