### ISSUE TITLE
Issue in Exercise 8 Task 2

### ISSUE THREAD

**Issue by shashankms9** [microsoft/MCW-Enterprise-class-networking#77]
[Exercise 8 Task 2 step 10](https://github.com/microsoft/MCW-Enterprise-class-networking/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Enterprise-class%20networking%20in%20Azure.md#task-2-configure-routing-for-simulated-on-premises-to-azure-traffic) When we try to add a subnet to the route tables as mentioned in the instruction(step 10), we have received below error.
 
Error message: `No available IP address in subnet GatewaySubnet`.

Please find the error screenshot below:

![image](https://user-images.githubusercontent.com/104433795/209909911-1920b865-5525-4b99-81f2-f7ba5ce92dbb.png)

You can find the available subnets and its configuration in the attached screenshot below:

![image](https://user-images.githubusercontent.com/104433795/209909898-8ec9389d-2aef-44be-9671-37d6cf0af49f.png)

**Comment by daneenec** [comment]
@shashankms9  @DawnmarieDesJardins We will have a resource available next week to further evaluate this issue.
