### ISSUE TITLE
Wrong routing information from 'OnPremVNet' to 'WGVNet2'

### ISSUE THREAD

**Issue by ataka309** [microsoft/MCW-Enterprise-class-networking#79]
* In exercise 8 - Task 2, on the 'on-premises' virtual machine (OnPremVM), unanble to connect 10.8.0.100 by http.
***
Due to lack of the routing information, asymmetric communication is occurring at 'WGVNet2'.
***
1. In exercise 2 - Task 1 we should configure the exchange of routing information as below.  
    [VNETPeering_WGVNet1-WGVNet2]Use this virtual network's gateway or Route Server
2. In exercise 4 - Task 2 we should configure the route to 'OnPremVNet' as below.  
    Route name: AppToOnpremises  
    Address prefix destination: IP Addresses  
    Address prefix: 192.168.2.0/27  
    Next hop type: Virtual appliance  
    Next hop address: 10.7.1.4 (This is the private IP of Azure Firewall.)

**Comment by DawnmarieDesJardins** [comment]
Added Sarah O for visibility

**Comment by sar2olson** [comment]
@DawnmarieDesJardins - can you please assign to crpietschmann for resolution?

**Comment by crpietschmann** [comment]
@ataka309 After testing this, I added "Exercise 7: Task 6: Update VNet peerings to use gateway" that updates the VNet Peerings to use the Gateway so traffic from the OnPremVM will be able to reach the Web App. This was the only configuration needed. Thanks.

FYI, @DawnmarieDesJardins @sar2olson

**Comment by ataka309** [comment]
@crpietschmann
Thanks a lot! I confirmed the discription of additional step.

But the asymmetric communication is occurring at 'WGVNet2' yet.
Could you try to connect from OnPremVM to WGWEB1 by RDP. I think you can not connect it.

So, you should add the step below.

------------------------------------------------------------------------------
In exercise 4 - Task 2 we should configure the route to 'OnPremVNet' as below.
Route name: AppToOnpremises
Address prefix destination: IP Addresses
Address prefix: 192.168.2.0/27
Next hop type: Virtual appliance
Next hop address: 10.7.1.4 (This is the private IP of Azure Firewall.)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #80

**Comment by ataka309** [comment]
Even if you add an "allow" rule to Azure Firewall, you can not connect by RDP.
In fact, I could not connect by RDP, althogh I could do by http.   
So I added the routing table, and finally I could reach out RGWEB1 by RDP (Of course I configured an "allow" rule before).

・ Azure Firewall blocks the connection (statement in Exercise 8 Task 2) → RDP＆HTTP are blocked
・ Insufficent routing table (no statement) → RDP is blocked (no effect to http)

But your description is not wrong, so it's ok. Thanks your coorporation!

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann 
Morning Chris.  Please review the comment above and advise.  Do we need an additional PR?
